### ISSUE TITLE
Fail to install microsoft r open 3.4.3 on ubuntu

### ISSUE THREAD

**Issue by brunoroquette** [Microsoft/microsoft-r-open#59] opened 2018-03-08 12:10 UTC
After run the ./install.sh command and answer yes for all questions, my system crashs on "Updating apt package repositories..."

**Comment by Neil-Schneider** [comment] 2018-03-08 14:32
I have only attempted the install in a docker container (ubuntu 16.04), but this works for me.

```
ENV mro=3.4.3
WORKDIR /tmp
RUN wget https://mran.blob.core.windows.net/install/mro/$mro/microsoft-r-open-$mro.tar.gz \
    && tar -xvf microsoft-r-open-$mro.tar.gz \
    && ./microsoft-r-open/install.sh -au \
    && rm -rf /tmp/*
```

**Comment by jeroenterheerdt** [comment] 2019-01-11 19:44
I can not reproduce this issue. Are you still having trouble? If not, I will go ahead and close this issue.

**Closed** 2019-01-14 22:59 UTC
