### ISSUE TITLE
Cannot install packages in R Console

### ISSUE THREAD

**Issue by giorjet** [Microsoft/microsoft-r-open#58] opened 2018-03-07 11:09 UTC
Hello 
I have  Microsoft R Open 3.4.2. When I try to install packages (any) I get the error message:

 

> install.packages("jsonlite")
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2017-10-15/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2017-10-15/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://mran.microsoft.com/snapshot/2017-10-15/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2017-10-15/src/contrib/PACKAGES'
Installing package into ‘C:/Users/utente/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://mran.microsoft.com/snapshot/2017-10-15/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2017-10-15/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘jsonlite’ is not available (for R version 3.4.2)
Warning in install.packages :
  unable to access index for repository https://mran.microsoft.com/snapshot/2017-10-15/bin/windows/contrib/3.4:
  cannot open URL 'https://mran.microsoft.com/snapshot/2017-10-15/bin/windows/contrib/3.4/PACKAGES'

>

**Comment by jeroenterheerdt** [comment] 2019-01-11 19:31
I cannot reproduce this. @giorjet  are you still having trouble? if not, I'll close this issue.

**Closed** 2019-01-14 22:59 UTC
